# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

"""
Compute subproject test dependencies from the consumer graph.

The consumer graph (therock_consumer_graph.json) is generated at CMake configure
time by therock_emit_consumer_graph() and committed to test_tools/ so that CI
change-detection jobs can read it without running cmake first.

Algorithm
---------
1. Load the consumer graph: { subproject: { consumers: [...] } }
2. Derive each subproject's build stage from the committed artifact-*.toml
   descriptors + BUILD_TOPOLOGY.toml (no CMake configure required).
3. For each changed subproject, add its same-stage direct consumers.
4. Apply include/exclude overrides from test_subprojects_overrides.json.

"Same-stage" means the consumer is in the same BUILD_TOPOLOGY build stage as
the changed subproject.  Cross-stage consumers are universal deps (ROCR-Runtime,
hip-clr, compiler); enumerating them here would pull in the whole test tree, so
they are cut. Where a specific cross-stage or test-only coupling must still be
tested, it is listed explicitly in test_subprojects_overrides.json (see the
overrides for hip-clr / ROCR-Runtime). Foundational deps that have no derivable
stage (e.g. rocm-core, rocm-cmake) also rely on explicit overrides, because the
same-stage cut selects nothing for a stage-less project.

Example
-------
$ python test_tools/determine_rocm_test_dependencies.py --changed-projects rocSPARSE
["hipsparse", "rocsparse", "rocsolver", "hipsolver"]
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(
    0, str(Path(__file__).resolve().parents[1] / "build_tools" / "github_actions")
)
from github_actions_api import gha_set_output

sys.path.insert(
    0, str(Path(__file__).resolve().parents[1] / "build_tools" / "_therock_utils")
)

_CONSUMER_GRAPH_NAME = "therock_consumer_graph.json"
_OVERRIDES_NAME = "test_subprojects_overrides.json"


def _load_consumer_graph(therock_dir: Path) -> dict:
    """Load the committed consumer graph JSON.

    Falls back to the build-directory copy if the committed copy is absent
    (useful during local development before a configure run).
    """
    committed = therock_dir / "test_tools" / _CONSUMER_GRAPH_NAME
    if committed.exists():
        return json.loads(committed.read_text())

    built = therock_dir / "build" / _CONSUMER_GRAPH_NAME
    if built.exists():
        print(
            f"Warning: using build-directory consumer graph ({built}). "
            "Run `python test_tools/determine_rocm_test_dependencies.py --regenerate` "
            "and commit test_tools/therock_consumer_graph.json.",
            file=sys.stderr,
        )
        return json.loads(built.read_text())

    raise FileNotFoundError(
        f"Consumer graph not found at {committed} or {built}.\n"
        "Either commit test_tools/therock_consumer_graph.json (generated by cmake) "
        "or run `cmake -B build ...` first."
    )


def _load_overrides(therock_dir: Path) -> dict:
    overrides_file = therock_dir / "test_tools" / _OVERRIDES_NAME
    if not overrides_file.exists():
        return {}
    data = json.loads(overrides_file.read_text())
    # Strip meta keys that start with "_". Lowercase keys and include/exclude
    # values so mixed-case override entries (e.g. "ROCR-Runtime") match the
    # lowercased changed-project names they are looked up by.
    normalized = {}
    for key, entry in data.items():
        if key.startswith("_"):
            continue
        normalized[key.lower()] = {
            "include": [c.lower() for c in entry.get("include", [])],
            "exclude": [c.lower() for c in entry.get("exclude", [])],
            "fanout_all_consumers": bool(entry.get("fanout_all_consumers", False)),
        }
    return normalized


def _stage_path_subproject(component_key: str) -> str | None:
    """Extract the subproject name from an artifact-*.toml component key.

    Component keys are stage-relative paths such as "math-libs/rocRAND/stage" or
    "dctools/rdc/stage/portable-rdc". The subproject is the path segment directly
    before the "stage" segment. Returns None if there is no "stage" segment.
    """
    parts = component_key.split("/")
    try:
        stage_idx = parts.index("stage")
    except ValueError:
        return None
    if stage_idx == 0:
        return None
    return parts[stage_idx - 1].lower()


def _build_stage_of_map(therock_dir: Path) -> dict[str, str]:
    """Return { subproject_lower -> build_stage }, derived from committed files.

    The mapping is resolved subproject -> artifact -> artifact_group -> build_stage
    with no CMake metadata and no configure step:
      * subproject -> artifact:  the artifact-*.toml `components."<path>/stage"`
        keys (the artifact name is the file stem minus the "artifact-" prefix).
      * artifact -> build_stage: BuildTopology.stage_of_artifact().

    Subprojects that appear in no artifact-*.toml (foundation libs, third-party
    host deps) have no derivable stage and are omitted; callers treat a missing
    stage as "do not apply the same-stage cut" and defer to overrides.
    """
    try:
        import tomllib
    except ModuleNotFoundError:  # Python <= 3.10
        import tomli as tomllib

    try:
        from build_topology import get_topology
    except ImportError:
        return {}

    try:
        topology = get_topology(therock_dir / "BUILD_TOPOLOGY.toml")
    except FileNotFoundError:
        return {}

    subproject_to_stage: dict[str, str] = {}
    for toml_path in therock_dir.rglob("artifact-*.toml"):
        if "/build/" in toml_path.as_posix():
            continue
        artifact_name = toml_path.stem.removeprefix("artifact-")
        stage = topology.stage_of_artifact(artifact_name)
        if not stage:
            continue
        data = tomllib.loads(toml_path.read_text())
        for entries in data.get("components", {}).values():
            if not isinstance(entries, dict):
                continue
            for component_key in entries:
                subproject = _stage_path_subproject(component_key)
                if subproject:
                    subproject_to_stage.setdefault(subproject, stage)
    return subproject_to_stage


def _apply_overrides(result: set, changed: list[str], overrides: dict) -> set:
    """Apply include/exclude overrides for all changed projects in one pass.

    Overrides are applied once, after all same-stage consumers have been
    gathered, so exclude semantics are order-independent: an exclude for one
    changed project is not silently undone by another changed project adding the
    same consumer earlier or later in iteration. All includes are unioned first,
    then all excludes are subtracted.
    """
    for proj in changed:
        entry = overrides.get(proj, {})
        result.update(entry.get("include", []))
    for proj in changed:
        entry = overrides.get(proj, {})
        result.difference_update(entry.get("exclude", []))
    return result


def get_subprojects_to_test(
    changed_subprojects: list[str], therock_dir: Path | None = None
) -> set[str]:
    """Return the set of subproject names (lowercase) to test."""
    if therock_dir is None:
        therock_dir = Path.cwd()
    else:
        therock_dir = Path(therock_dir)

    graph = _load_consumer_graph(therock_dir)
    overrides = _load_overrides(therock_dir)
    stage_of = _build_stage_of_map(therock_dir)

    changed_lower = [p.lower() for p in changed_subprojects]

    # Warn on unrecognized projects (false-green typo guard).
    known = set(graph.keys())
    unknown = [p for p in changed_lower if p not in known]
    if unknown:
        print(
            f"Warning: unrecognized project(s) {unknown}; "
            "no tests will be selected for them",
            file=sys.stderr,
        )

    result = set(changed_lower)
    for proj in changed_lower:
        entry = graph.get(proj, {})
        consumers = entry.get("consumers", [])

        # Foundational fan-out: a project flagged fanout_all_consumers in the
        # overrides file selects ALL its graph consumers, bypassing the
        # same-stage cut. This is the opt-in for stage-less foundational deps
        # (rocm-cmake, rocm-core, ...) whose consumers span every stage and
        # would otherwise be selected by nothing. It must stay explicit per
        # project: blanket-fanning every stage-less project would re-expand
        # universal deps (hip-clr, therock-googletest) into the whole test tree.
        if overrides.get(proj, {}).get("fanout_all_consumers"):
            result.update(consumers)
            continue

        proj_stage = stage_of.get(proj)

        # A stage-less project (proj_stage is None: foundational deps like
        # rocm-core/rocm-cmake with no artifact-*.toml) selects no consumers via
        # the same-stage cut; its dependents are covered by an explicit
        # fanout_all_consumers flag or include entries in
        # test_subprojects_overrides.json instead.
        for consumer in consumers:
            # Same-stage consumers only.  Cross-stage deps (ROCR-Runtime,
            # hip-clr, compiler) would pull in the whole test tree; specific
            # cross-stage/test-only couplings that must run are listed in the
            # overrides file rather than enumerated here.
            if proj_stage and stage_of.get(consumer) == proj_stage:
                result.add(consumer)

    # Apply overrides once, after all same-stage consumers are gathered, so
    # exclude is order-independent across multiple changed projects.
    result = _apply_overrides(result, changed_lower, overrides)

    return result


def list_subprojects(therock_dir: Path | None = None, show_deps: bool = False):
    """List all subprojects known to the consumer graph."""
    if therock_dir is None:
        therock_dir = Path.cwd()

    graph = _load_consumer_graph(Path(therock_dir))

    if show_deps:
        return {
            name: (entry["consumers"] if entry.get("consumers") else "empty")
            for name, entry in sorted(graph.items())
        }
    return sorted(graph.keys())


def _normalize_graph_json(raw: str) -> str:
    """Return canonical JSON text for a consumer graph.

    The CMake emitter writes compact inline arrays; the committed copy uses
    json.dumps formatting. Normalizing both through the same serializer (sorted
    keys, sorted consumer lists, 2-space indent) means the drift-lint `git diff`
    only fires on real content changes, not formatting differences.
    """
    data = json.loads(raw)
    canonical = {
        key: {"consumers": sorted(entry.get("consumers", []))}
        for key, entry in sorted(data.items())
    }
    return json.dumps(canonical, indent=2) + "\n"


def regenerate_consumer_graph(therock_dir: Path) -> Path:
    """Write the build-directory graph to test_tools/ in canonical form.

    Requires that cmake has already been run so build/therock_consumer_graph.json
    exists. The output is normalized (see _normalize_graph_json) so the committed
    copy is stable regardless of the emitter's raw formatting.
    """
    src = therock_dir / "build" / _CONSUMER_GRAPH_NAME
    if not src.exists():
        raise FileNotFoundError(
            f"Build-directory consumer graph not found at {src}.\n"
            "Run `cmake -B build ...` first."
        )
    dst = therock_dir / "test_tools" / _CONSUMER_GRAPH_NAME
    dst.write_text(_normalize_graph_json(src.read_text()))
    print(f"Wrote canonical consumer graph {src} -> {dst}")
    return dst


def main():
    parser = argparse.ArgumentParser(
        description="Compute subproject test dependencies from the consumer graph"
    )
    parser.add_argument(
        "--therock-dir", type=str, default=".", help="TheRock directory"
    )
    parser.add_argument(
        "--changed-projects",
        type=str,
        nargs="*",
        metavar="PROJECT",
        help="Project(s) that changed. Accepts space- or comma-separated list. "
        "Supports 'rocblas' or 'projects/rocblas' format.",
    )
    parser.add_argument(
        "--list-subprojects", action="store_true", help="List all known subprojects"
    )
    parser.add_argument(
        "--show-deps",
        action="store_true",
        help="With --list-subprojects, show consumers (or 'empty' if none)",
    )
    parser.add_argument(
        "--format",
        choices=["json", "list"],
        default="json",
        help="Output format: json (default) or list (newline-separated)",
    )
    parser.add_argument(
        "--gha-output",
        action="store_true",
        help="Write projects_to_test to GITHUB_OUTPUT",
    )
    parser.add_argument(
        "--regenerate",
        action="store_true",
        help="Copy build/therock_consumer_graph.json to test_tools/ for committing",
    )

    args = parser.parse_args()
    therock_dir = Path(args.therock_dir).resolve()

    if args.regenerate:
        regenerate_consumer_graph(therock_dir)
        return

    if args.list_subprojects:
        result = list_subprojects(therock_dir, show_deps=args.show_deps)
        print(json.dumps(result, indent=2))
        return

    # Parse and normalize changed_projects
    changed = args.changed_projects
    if changed:
        flattened = []
        for item in changed:
            flattened.extend(p.strip() for p in item.split(",") if p.strip())
        changed = flattened

    if changed:
        changed = [p.removeprefix("projects/") for p in changed]

    # No projects specified → all tests
    if not changed:
        if args.gha_output:
            gha_set_output({"projects_to_test": "*"})
        else:
            print("*")
        return

    result = get_subprojects_to_test(changed, therock_dir)
    projects_to_test = ",".join(sorted(result))

    if args.gha_output:
        gha_set_output({"projects_to_test": projects_to_test})
    elif args.format == "json":
        print(json.dumps(sorted(result)))
    else:
        for item in sorted(result):
            print(item)


if __name__ == "__main__":
    main()
